version: '3'

services:
    php-apache:
        build: env-config/php
        container_name: laravel-php-apache
        hostname: "laravel"
        ports: 
            - "8088:80"
        volumes: 
            - ./src:/var/www/html/
            - ./env-config/apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./env-config/php/php.ini:/usr/local/etc/php/php.ini
        working_dir: /var/www/html

    mysql:
        image: mysql:5.7
        container_name: laravel-mysql
        volumes: 
            - /srv/docker/mysql/laravel:/var/lib/mysql
        ports:
            - "3336:3306"
        environment:            
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=secret

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel-phpmyadmin
        ports:
            - "8089:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        depends_on:
            - "mysql"
        volumes:
            - ./env-config/php/php.ini:/usr/local/etc/php/php.ini
            - ./env-config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
   
      
